apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: grpc
  selector:
    app: users
    version: v1
